import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "./_components/Navbar";
import { Suspense } from "react";
import GlobalQueryProvider from "./_components/providers/GlobalQueryProvider";
import AppProvider from "./_components/providers/AppProvider";
import { SessionProvider } from "next-auth/react";

const poppins = Poppins({
  subsets: ["latin"],
  weight:['500','600','700']
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} h-full`}>
      <body className="h-screen flex flex-col bg-(--background)">
        <GlobalQueryProvider>
          <SessionProvider>
            <AppProvider>
              <Toaster />
              <div id="root"></div>
              <Suspense>
                <Navbar />
              </Suspense>
              {children}
            </AppProvider>
          </SessionProvider>
        </GlobalQueryProvider>
      </body>
    </html>
  );
}
