import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "./_components/Navbar";
import { Suspense } from "react";
import GlobalQueryProvider from "./_components/providers/GlobalQueryProvider";
import AppProvider from "./_components/providers/AppProvider";
import { SessionProvider } from "next-auth/react";
import SocketProvider from "./_components/providers/SocketProvider";
import VideoCallProvider from "./_components/providers/VideoCallProvider";
import Socket, { CallingFnProvider } from "./_components/socket-listeners/Socket";
import VideoCallWrapper from "./_components/video_call/VideoCallWrapper";
import UserProvider from "./_components/providers/UserProvider";
import PhoneNav from "./_components/navbar/PhoneNav";
import PhoneTopBar from "./_components/navbar/PhoneTopBar";
import PlaceHolderDiv from "./_components/PlaceHolderDiv";

const poppins = Poppins({
  subsets: ["latin"],
  weight:['500','600','700']
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className}`}>
      <body className=" bg-(--bg-main)">
        <GlobalQueryProvider>
          <SessionProvider>
            <UserProvider>
              <SocketProvider>
                <AppProvider>
                  <VideoCallProvider>
                    <CallingFnProvider>
                      {/* <Socket /> */}
                      <Toaster />
                      <VideoCallWrapper />
                      <div id="root"></div>
                      <div id="video"></div>
                      <Suspense>
                        <Navbar />
                        <div className="  h-full flex flex-col">
                          <PhoneTopBar />
                          <div className="">{children}</div>
                          <PlaceHolderDiv />
                        </div>
                        <PhoneNav />
                      </Suspense>
                    </CallingFnProvider>
                  </VideoCallProvider>
                </AppProvider>
              </SocketProvider>
            </UserProvider>
          </SessionProvider>
        </GlobalQueryProvider>
      </body>
    </html>
  );
}
